# Generated by Django 3.2.7 on 2021-09-24 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='/user_avatars/default_img.jpeg', upload_to='user_avatars')),
                ('info', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('posts_count', models.IntegerField(default=0)),
                ('subscribes_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
