# Generated by Django 3.2.7 on 2021-09-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210926_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='posts_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscribes_count',
        ),
    ]
