# Generated by Django 3.2.7 on 2021-09-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
