# Generated by Django 3.2.7 on 2021-09-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_like_created_at'),
        ('instagram', '0006_comment_created_at'),
    ]

    operations = [
    ]
