# Generated by Django 3.2.7 on 2021-09-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_merge_0005_like_created_at_0006_comment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='liked_user',
            new_name='user',
        ),
    ]
